import categorImg_1 from '../assets/Images/categor-img-1.png'
import categorImg_2 from '../assets/Images/categor-img-2.png'
import categorImg_3 from '../assets/Images/categor-img-3.png'
import categorImg_4 from '../assets/Images/categor-img-4.png'
import categorImg_5 from '../assets/Images/categor-img-5.png'
import categorImg_6 from '../assets/Images/categor-img-6.png'
import categorImg_7 from '../assets/Images/categor-img-7.png'
import categorImg_8 from '../assets/Images/categor-img-8.png'
import categorImg_9 from '../assets/Images/categor-img-9.png'
import categorImg_10 from '../assets/Images/categor-img-10.png'
import categorImg_11 from '../assets/Images/categor-img-11.png'

const categorObj = [
  {
    id: 1,
    img: 'https://imgur.com/lkpKu0h.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', '“Ajdar”ning tab'],
      ['https://imgur.com/AreV92z.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/wcqk9Qd.png', 'Ruhlar isyoni'],
    ],
    name: `Abdulla Avloniy`,
    year: '1878-1934',
    book: 34,
    player: 13,
    categor: 'Temuriylar davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 2,
    name: `Nusrat Rahmat`,
    year: '1878-1934',
    img: 'https://imgur.com/l9cSZQG.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', '“Ajdar”ning tab'],
      ['https://imgur.com/AreV92z.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/wcqk9Qd.png', 'O’tkan kunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Mustaqillik davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 3,
    name: `Rahmonberdi Madazimov`,
    year: '1878-1934',
    img: 'https://imgur.com/r53er8X.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', '“Ajdar”ning tab'],
      ['https://imgur.com/AreV92z.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/wcqk9Qd.png', 'O’tkan kunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Temuriylar davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 4,
    name: `Hamza Hakimzoda Niyoziy`,
    year: '1878-1934',
    img: 'https://imgur.com/4Bu4xJS.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', '“Ajdar”ning tab'],
      ['https://imgur.com/AreV92z.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/wcqk9Qd.png', 'O’tkan kunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Sovet davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 5,
    name: `Abdulhamid Cho'lpon`,
    year: '1878-1934',
    img: 'https://imgur.com/xiJqf5u.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', '“Ajdar”ning tab'],
      ['https://imgur.com/AreV92z.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/wcqk9Qd.png', 'O’tkan kunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Sovet davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 6,
    name: `Abdurauf Fitrat`,
    year: '1878-1934',
    img: 'https://imgur.com/KdS6fSv.png',
    userbooks: [
      ['https://imgur.com/0w41BI7.png', 'Ikki eshik orasi'],
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/AreV92z.png', 'Ajdodlarimiz fojia..'],
    ],
    book: 34,
    player: 13,
    categor: 'Temuriylar davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 7,
    name: `Abdulmajid Qodiriy`,
    year: '1878-1934',
    img: 'https://imgur.com/ouwQQgq.png',
    userbooks: [
      ['https://imgur.com/0w41BI7.png', 'Ikki eshik orasi'],
      ['https://imgur.com/LhSJArl.png', '“Ajdar”ning tab'],
      ['https://imgur.com/8JrTbZY.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/AreV92z.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/qjqOb1C.png', 'Yulduzli tunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Sovet davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 8,
    name: `Munavvarqori Abdurashidxonov`,
    year: '1878-1934',
    img: 'https://imgur.com/x4OurOD.png',
    userbooks: [
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/LhSJArl.png', '“Ajdar”ning tab'],
      ['https://imgur.com/8JrTbZY.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/AreV92z.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/qjqOb1C.png', 'Yulduzli tunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Mustaqillik davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 9,
    name: `Abdulla Qodiriy`,
    year: '1878-1934',
    img: 'https://imgur.com/T6dKlez.png',
    userbooks: [
      ['https://imgur.com/0w41BI7.png', 'Ikki eshik orasi'],
      ['https://imgur.com/LhSJArl.png', '“Ajdar”ning tab'],
      ['https://imgur.com/8JrTbZY.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/AreV92z.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/SVzOEm2.png', 'O’tkan kunlar'],
    ],
    book: 34,
    player: 13,
    categor: 'Temuriylar davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 10,
    name: `Mahmuxo’ja Behbudiy`,
    year: '1878-1934',
    img: 'https://imgur.com/IrujoLP.png',
    userbooks: [
      ['https://imgur.com/hIB4JBz.png', 'Dunyoning ishlari'],
      ['https://imgur.com/0w41BI7.png', 'Ikki eshik orasi'],
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/qjqOb1C.png', 'Yulduzli tunlar'],
      ['https://imgur.com/wcqk9Qd.png', 'Ruhlar isyoni'],
      ['https://imgur.com/MDWOJqm.png', 'UFq'],
    ],
    book: 34,
    player: 13,
    categor: 'Mustaqillik davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
  {
    id: 11,
    name: `Hoji Muin`,
    year: '1878-1934',
    img: 'https://imgur.com/NIvhCPn.png',
    userbooks: [
      ['https://imgur.com/hIB4JBz.png', 'Dunyoning ishlari'],
      ['https://imgur.com/D7bDALW.png', 'Tushda kechgan umrlar'],
      ['https://imgur.com/8JrTbZY.png', 'Ulug’bek Xazinasi'],
      ['https://imgur.com/qjqOb1C.png', 'Ajdodlarimiz fojia..'],
      ['https://imgur.com/SVzOEm2.png', 'Yulduzli tunlar'],
      ['https://imgur.com/MDWOJqm.png', 'UFq'],
    ],
    book: 34,
    player: 13,
    categor: 'Sovet davri',
    desc: 'Oʻtkir Hoshimov 1941 yil Toshkent viloyatining Zangiota (hozirgi Chilonzor) tumanidagi Doʻmbiravot mavzeida tugʻildi. Oʻ. Hoshimov mehnat faoliyatini erta boshladi. Toshkent Davlat universiteti (hozirgi Oʻzbekiston Milliy universiteti)ning jurnalistika kulliyotida oʻqish bilan baravar gazeta tahririyatida ishladi. 1959 yildan 1963 yilgacha “Temiryoʻlchi”, “Qizil Oʻzbekiston”, “Transportniy rabochiy” gazetalarida xat tashuvchi, mussaxhih, tarjimon boʻlib ishladi. Soʻng “Toshkent haqiqati” gazetasida adabiy xodim (1963–1966), “Toshkent oqshomi” gazetasida boʻlim mudiri (1966–1982), Gʻ. Gʻulom nomidagi Adabiyot va sanʼat nashriyotida bosh muharrir oʻrinbosari (1982–1985) boʻldi. 1985–1995 yillarda “Sharq yulduzi” jurnaliga bosh muharrirlik qildi. 1995 yildan 2005 yilgacha Oʻzbekiston Respublikasi Oliy Majlisining Matbuot va axborot qoʻmitasi raisi lavozimida ishladi. 2005 yildan “Teatr“ jurnalida bosh muharrir boʻlib ishladi.',
  },
]

export default categorObj